language: node_js

node_js:
  - "stable"
  
before_install:
  # Install Gitbook
  - npm install gitbook-cli -g
  
before_script:
  # Clone the repository
  - cd ~
  # git clone --branch master git@github.com:hznanhai/Akka-Essentials-in-Chinese.git
  - git clone --branch gh-pages https://github.com/hznanhai/Akka-Essentials-in-Chinese.git book
  
script:
  # Build gitbook
  - cd ~/Akka-Essentials-in-Chinese
  - gitbook build
  # Cp built book to gh-pages branch && commit
  - cp ~/Akka-Essentials-in-Chinese/_book/* ~/book/
  - cd ~/book
  - git commit -a -m "update"
  - git push
  
branches:
  only:
    - master

