language: node_js

node_js:
  - "stable"
  
before_install:
  - BASE_PATH=`pwd`
  
  # Install Gitbook
  - npm install gitbook-cli -g
  
before_script:
  # Clone the repository
  - cd $BASE_PATH
  # git clone --branch master git@github.com:hznanhai/Akka-Essentials-in-Chinese.git
  - git clone --branch gh-pages https://github.com/hznanhai/Akka-Essentials-in-Chinese.git $BASE_PATH/book
  
script:
  # Build gitbook
  - cd $BASE_PATH/Akka-Essentials-in-Chinese
  - gitbook build
  # Cp built book to gh-pages branch && commit
  - cp $BASE_PATH/Akka-Essentials-in-Chinese/_book/* $BASE_PATH/book/
  - cd $BASE_PATH/book
  - git commit -a -m "update"
  - git push
  
branches:
  only:
    - master

